export const initialStoreTemplates = [
  {
    category: {
      name: "Moda",
      slug: "moda",
      description: "Roupas, calçados, acessórios e coleções sazonais.",
    },
    template: {
      name: "Fashion Premium",
      slug: "fashion-premium",
      description: "Vitrine elegante para marcas de moda.",
      primaryColor: "#111827",
      secondaryColor: "#f8fafc",
      accentColor: "#ec4899",
      bannerTitle: "Nova coleção disponível",
      bannerSubtitle: "Peças selecionadas para vender com estilo e sofisticação.",
      defaultCategories: ["Roupas", "Calçados", "Acessórios"],
      defaultProducts: [
        ["Camiseta Premium", "Algodão macio para o dia a dia", 89.9, "Roupas"],
        ["Jaqueta Cropped", "Peça moderna para compor looks urbanos", 219.9, "Roupas"],
        ["Vestido Midi", "Caimento elegante para ocasiões especiais", 189.9, "Roupas"],
        ["Tênis Urban", "Conforto e estilo para sua rotina", 249.9, "Calçados"],
        ["Sandália Classic", "Design leve para dias quentes", 129.9, "Calçados"],
        ["Bolsa Classic", "Acabamento elegante e versátil", 179.9, "Acessórios"],
        ["Óculos Fashion", "Acessório marcante para qualquer look", 99.9, "Acessórios"],
        ["Cinto Premium", "Detalhe sofisticado para finalizar o visual", 69.9, "Acessórios"],
      ],
    },
  },
  {
    category: {
      name: "Beleza",
      slug: "beleza",
      description: "Cosméticos, skincare, maquiagem e autocuidado.",
    },
    template: {
      name: "Beauty Glow",
      slug: "beauty-glow",
      description: "Layout luminoso para produtos de beleza.",
      primaryColor: "#7c2d12",
      secondaryColor: "#fff7ed",
      accentColor: "#fb7185",
      bannerTitle: "Realce sua beleza todos os dias",
      bannerSubtitle: "Produtos essenciais para autocuidado e rotina de beleza.",
      defaultCategories: ["Skincare", "Maquiagem", "Perfumes"],
      defaultProducts: [
        ["Sérum Facial", "Hidratação leve com acabamento natural", 69.9, "Skincare"],
        ["Creme Noturno", "Cuidado intenso para pele renovada", 89.9, "Skincare"],
        ["Máscara Glow", "Tratamento rápido para luminosidade", 49.9, "Skincare"],
        ["Batom Matte", "Cor intensa com longa duração", 39.9, "Maquiagem"],
        ["Paleta Nude", "Tons versáteis para todos os dias", 119.9, "Maquiagem"],
        ["Perfume Floral", "Fragrância delicada e marcante", 149.9, "Perfumes"],
        ["Body Splash", "Frescor leve para a rotina", 59.9, "Perfumes"],
        ["Kit Autocuidado", "Seleção especial para presentear", 129.9, "Skincare"],
      ],
    },
  },
  {
    category: {
      name: "Eletrônicos",
      slug: "eletronicos",
      description: "Gadgets, acessórios, informática e tecnologia.",
    },
    template: {
      name: "Tech Store",
      slug: "tech-store",
      description: "Template moderno para eletrônicos.",
      primaryColor: "#020617",
      secondaryColor: "#e0f2fe",
      accentColor: "#38bdf8",
      bannerTitle: "Tecnologia para facilitar sua vida",
      bannerSubtitle: "Ofertas em acessórios, gadgets e produtos inteligentes.",
      defaultCategories: ["Acessórios", "Informática", "Smart Home"],
      defaultProducts: [
        ["Fone Bluetooth", "Som limpo e bateria para o dia todo", 159.9, "Acessórios"],
        ["Carregador Turbo", "Carga rápida para seus dispositivos", 79.9, "Acessórios"],
        ["Cabo USB-C Pro", "Resistente e pronto para carga rápida", 39.9, "Acessórios"],
        ["Mouse Sem Fio", "Precisão e conforto no trabalho", 89.9, "Informática"],
        ["Teclado Compacto", "Produtividade com design minimalista", 139.9, "Informática"],
        ["Webcam Full HD", "Imagem nítida para reuniões e lives", 199.9, "Informática"],
        ["Lâmpada Smart", "Controle sua iluminação pelo celular", 69.9, "Smart Home"],
        ["Tomada Inteligente", "Automação simples para sua casa", 59.9, "Smart Home"],
      ],
    },
  },
  {
    category: {
      name: "Pet Shop",
      slug: "pet-shop",
      description: "Produtos para pets, rações, brinquedos e cuidados.",
    },
    template: {
      name: "Pet Friendly",
      slug: "pet-friendly",
      description: "Vitrine simpática para pet shops.",
      primaryColor: "#14532d",
      secondaryColor: "#f0fdf4",
      accentColor: "#f59e0b",
      bannerTitle: "Tudo para cuidar do seu melhor amigo",
      bannerSubtitle: "Produtos selecionados para conforto, diversão e saúde pet.",
      defaultCategories: ["Rações", "Brinquedos", "Higiene"],
      defaultProducts: [
        ["Ração Premium", "Nutrição equilibrada para pets saudáveis", 119.9, "Rações"],
        ["Petisco Natural", "Recompensa saborosa e nutritiva", 29.9, "Rações"],
        ["Ração Filhotes", "Fórmula especial para crescimento", 99.9, "Rações"],
        ["Brinquedo Interativo", "Diversão e estímulo todos os dias", 49.9, "Brinquedos"],
        ["Bolinha Resistente", "Ideal para brincadeiras ao ar livre", 24.9, "Brinquedos"],
        ["Arranhador Compacto", "Entretenimento para gatos", 89.9, "Brinquedos"],
        ["Shampoo Pet", "Cuidado suave para banho em casa", 34.9, "Higiene"],
        ["Tapete Higiênico", "Praticidade para a rotina do pet", 69.9, "Higiene"],
      ],
    },
  },
  {
    category: {
      name: "Casa e Decoração",
      slug: "casa-decoracao",
      description: "Decoração, utilidades domésticas e itens para casa.",
    },
    template: {
      name: "Casa Clean",
      slug: "casa-clean",
      description: "Layout aconchegante para casa e decoração.",
      primaryColor: "#292524",
      secondaryColor: "#fafaf9",
      accentColor: "#a3e635",
      bannerTitle: "Transforme sua casa com estilo",
      bannerSubtitle: "Itens escolhidos para ambientes bonitos e funcionais.",
      defaultCategories: ["Decoração", "Cozinha", "Organização"],
      defaultProducts: [
        ["Vaso Decorativo", "Design minimalista para qualquer ambiente", 79.9, "Decoração"],
        ["Luminária Mesa", "Iluminação aconchegante para sua casa", 149.9, "Decoração"],
        ["Quadro Botânico", "Toque natural para paredes elegantes", 89.9, "Decoração"],
        ["Kit Cozinha", "Utensílios práticos para o dia a dia", 99.9, "Cozinha"],
        ["Tábua Gourmet", "Madeira premium para servir e preparar", 69.9, "Cozinha"],
        ["Potes Herméticos", "Alimentos organizados por mais tempo", 79.9, "Cozinha"],
        ["Organizador", "Mais espaço e praticidade em casa", 59.9, "Organização"],
        ["Cesto Multiuso", "Organização com visual moderno", 49.9, "Organização"],
      ],
    },
  },
];
